[build]
	command = "npm run build"
	publish = "build"
[[headers]]
    for = "/api/*"
[headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, DELETE"
    Access-Control-Allow-Headers = "Content-Type"
